#leaflet 사용자 패키지
install.packages("htmltools")
install.packages("leaflet")
library(htmltools)
library(dplyr)
library(leaflet)

#1 경기도 주요 도시의 공유재산 수량 및 분포
m0 <- data.frame()
m1 <- read.csv("Gapyeong.csv")
m1$longitude <-as.numeric(m1$longitude)
m1$latitude <-as.numeric(m1$latitude)
m1$area <- as.character(m1$area)
m2 <- read.csv("Goyang.csv")
m2$longitude <-as.numeric(m2$longitude)
m2$latitude <-as.numeric(m2$latitude)
m2$area <- as.character(m2$area)
m3 <- read.csv("Gwangju.csv")
m3$longitude <-as.numeric(m3$longitude)
m3$latitude <-as.numeric(m3$latitude)
m3$area <- as.character(m3$area)
m4 <- read.csv("Gimpo.csv")
m4$latitude <- as.character(m4$latitude)
m4$latitude <- as.numeric(m4$latitude)
m4$longitude <-as.numeric(m4$longitude)
m4$area <- as.character(m4$area)
m5 <- read.csv("Namyangju.csv")
m5$longitude <-as.numeric(m5$longitude)
m5$latitude <-as.numeric(m5$latitude)
m5$area <- as.character(m5$area)

m0 <- rbind(m1, m2, m3, m4, m5)
m0$avg_price <- (m0$대장가액.원./m0$재산면적)
m0 <- data.frame(m0$latitude, m0$longitude, m0$공부지목명, m0$재산면적, m0$대장가액.원., m0$avg_price, m0$area)
colnames(m0) <- c('lat', 'lon', 'assets_name', 'size', 'tot_price', 'avg_price', 'area')
m0$size <- ifelse(is.na(m0$size), 1, m0$size)
m0$avg_price <- ifelse(is.na(m0$avg_price), 0, m0$avg_price)
m0$avg_price <- ifelse(m0$avg_price == "Inf", 1, m0$avg_price)
m0$avg_price = round(m0$avg_price)
m0$assets_name <- as.character(m0$assets_name)
m0$popup <- paste("assets_name: ", m0$assets_name, " size: ", 
                  m0$size, " tot_price: ", m0$tot_price, " avg_price: ", m0$avg_price, " area: ", m0$area)

op <- leaflet(m0)
op <- op %>% addTiles() %>% setView(lng = 127.00953, lat = 37.274627, zoom = 8)
op %>% addTiles() %>% addMarkers(~lon, ~lat, clusterOptions = markerClusterOptions(), popup = ~htmlEscape(popup))
